name: chapa_unofficial
description: Flutter library that provides integration with the Chapa payment gateway.
version: 0.0.3
repository: https://github.com/mrnpro/ChapaFlutter


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.2.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  mockito: ^5.4.2
 
flutter:
